name: cnn
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - expat=2.6.3
  - intel-openmp=2023.1.0
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.4
  - numexpr=2.10.1
  - openssl=3.0.15
  - pandas=2.2.2
  - pip=24.2
  - python=3.12.5
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - readline=8.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - albucore==0.0.20
      - albumentations==1.4.21
      - annotated-types==0.7.0
      - attrs==24.2.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - efficientnet-pytorch==0.7.1
      - eval-type-backport==0.2.0
      - filelock==3.13.1
      - fonttools==4.54.1
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - grad-cam==1.5.4
      - grpcio==1.67.1
      - huggingface-hub==0.26.2
      - idna==3.10
      - jinja2==3.1.3
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lightning-utilities==0.11.8
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - munch==4.0.0
      - networkx==3.2.1
      - numpy==1.26.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - packaging==24.1
      - pillow==10.2.0
      - pretrainedmodels==0.7.4
      - propcache==0.2.0
      - protobuf==5.28.3
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pyparsing==3.2.0
      - pytorch-lightning==2.1.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - safetensors==0.4.5
      - scikit-learn==1.6.1
      - scipy==1.14.1
      - segmentation-models-pytorch==0.3.4
      - simsimd==5.9.9
      - stringzilla==3.10.7
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - timm==0.9.7
      - torch==2.2.1
      - torchaudio==2.2.1
      - torchmetrics==1.5.1
      - torchvision==0.17.1
      - tqdm==4.66.6
      - ttach==0.0.3
      - typing-extensions==4.9.0
      - urllib3==2.2.3
      - werkzeug==3.1.0
      - yarl==1.17.1
